### add
POST http://localhost:8080/role/add
Content-Type: application/json

{
  "id": 0,
  "name": "1111",
  "default_route": "1111",
  "status": false
}

### del
POST http://localhost:8080/role/del
Content-Type: application/json

{
"id": 39,
"name": "1111",
"default_route": "1111",
"status": false
}


### edit
POST http://localhost:8080/role/edit
Content-Type: application/json

{
  "id": 38,
  "name": "1212",
  "default_route": "2222",
  "status": true
}

### one
POST http://localhost:8080/role/one
Content-Type: application/json

{
  "id": 0
}

### one
POST http://localhost:8080/user_role/one
Content-Type: application/json

{
  "user_id": 1,
  "role_id": 2
}

### one
POST http://localhost:8080/role/one
Content-Type: application/json

{
  "id": 5

}


