//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub mod prelude;

pub mod sys_api;
pub mod sys_dictionary;
pub mod sys_dictionary_detail;
pub mod sys_menu;
pub mod sys_role;
pub mod sys_role_menu;
pub mod sys_user;
pub mod sys_user_role;
