//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sys_dictionary")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: Option<String>,
    pub alias: Option<String>,
    pub desc: Option<String>,
    pub status: Option<bool>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::sys_dictionary_detail::Entity")]
    SysDictionaryDetail,
}

impl Related<super::sys_dictionary_detail::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SysDictionaryDetail.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
